add composer tag
agallou/atoum-standard-edition pull request #13
Opened 2016-10-19 17:31 UTC by Grummfy

* composer tag
* author name
* other improvements

2016-10-25 19:58 UTC, agallou commented on composer.json
> +    "authors": [
does adding authors will limit contributions ? plus this a a team repo, it's not only mine. should we keep that ? (also, if we keep it, the real name si prefered in the composer.json : https://getcomposer.org/doc/04-schema.md#authors )

2016-10-25 20:08 UTC, Grummfy commented
here we are. I have removed the author tag

2016-10-25 20:13 UTC, agallou commented on composer.json
> +    "type": "package",
there is no reference of a "package" type on https://getcomposer.org/doc/04-schema.md#type 
were dit you found it ?

2016-10-25 20:24 UTC, Grummfy commented on composer.json
> +    "type": "package",
it could be anything

2016-10-25 20:30 UTC, agallou commented on composer.json
> +    "type": "package",
"Only use a custom type if you need custom logic during installation" : there is no custom logic, maybe we should remove this attribute.

2016-11-13 12:26 UTC, jubianchi requested changes

2016-11-13 12:26 UTC, jubianchi commented on composer.json
> +    "keywords": ["TDD","atoum","test","unit testing","atoum-edition"],
please, could you add a space after each comma :)

2016-11-13 12:27 UTC, jubianchi approved these changes

2016-11-13 12:27 UTC, merged